// The responsibility of managing product details and adding it to the cart now belongs to this class, so it needs these tools.
import { setLocalStorage, getLocalStorage } from "./utils.mjs";


export default class ProductDetails {
  constructor(productId, dataSource) {
    this.productId = productId;
    this.product = {};
    this.dataSource = dataSource;
  }


  async init() {
    // Fetches the specific product details using the ID
    // To load the full data (name, price, image) BEFORE attempting to render the HTML on the screen.
    this.product = await this.dataSource.findProductById(this.productId);
   
    // Renders the HTML on the page
    // Inject the content inside the <main> tag
    this.renderProductDetails("main");


    // Adds the event listener to the button
    // The "Add to Cart" button does not exist in the original HTML; it is dynamically generated by JS. Therefore, we can only attach the click event AFTER the previous step (render).
    // .bind(this) ensures that when clicked, the function knows that "this" refers to the ProductDetails class.
    document
      .getElementById("addToCart")
      .addEventListener("click", this.addToCart.bind(this));
  }


 /*  addToCart() {
    // This logic was previously in product.js
    // Encapsulation. It is good practice to keep everything related to product actions inside the class that manages it.
    let cartItems = getLocalStorage("so-cart");
   
    if (!cartItems) {
      cartItems = [];
    }
   
    cartItems.push(this.product);
    setLocalStorage("so-cart", cartItems);

    const badge = document.getElementById("cart-count");
    if (badge) {
      badge.textContent = cartItems.length;
      badge.style.display = "flex";
    }
  } */
addToCart() {
    // This logic was previously in product.js
    // Encapsulation. It is good practice to keep everything related to product actions inside the class that manages it.
    let cartItems = getLocalStorage("so-cart") || [];
    
    // 1. Check if the item is already in the cart using its ID
    const existingItem = cartItems.find((item) => item.Id === this.product.Id);

    if (existingItem) {
      // 2. If it exists, increment its quantity
      existingItem.Quantity = (existingItem.Quantity || 1) + 1;
    } else {
      // 3. If it's a new item, assign Quantity = 1 and push it
      this.product.Quantity = 1;
      cartItems.push(this.product);
    }
    
    // 4. Save the updated array back to LocalStorage
    setLocalStorage("so-cart", cartItems);

    // 5. Update the visual badge with the total quantity of items
    const badge = document.getElementById("cart-count");
    if (badge) {
      // Calculate total physical items using reduce
      const totalQuantity = cartItems.reduce((total, item) => total + (item.Quantity || 1), 0);
      badge.textContent = totalQuantity;
      badge.style.display = "flex";
    }
  }

  renderProductDetails(selector) {
    // Generates HTML using the properties of this.product object
    // This replaces the need for files like "marmot-ajax-3.html". The data comes from JSON and fills this template.
    const element = document.querySelector(selector);
   
    // Property names (Brand.Name, NameWithoutBrand, etc.) are based on the structure of your JSON file.
    const html = `
      <section class="product-detail">
        <h3>${this.product.Brand.Name}</h3>
        <h2 class="divider">${this.product.NameWithoutBrand}</h2>
        <img
          class="divider"
          src="${this.product.Images.PrimaryLarge}"
          alt="${this.product.NameWithoutBrand}"
        />
        <p class="product-card__price">$${this.product.FinalPrice}</p>
        <p class="product__color">${this.product.Colors[0].ColorName}</p>
        <p class="product__description">
          ${this.product.DescriptionHtmlSimple}
        </p>
        <div class="product-detail__add">
          <button id="addToCart" data-id="${this.product.Id}">Add to Cart</button>
        </div>
      </section>`;
     
    element.insertAdjacentHTML("afterBegin", html);
  }
}
