// The responsibility of managing product details and adding it to the cart now belongs to this class, so it needs these tools.
import { setLocalStorage, getLocalStorage } from "./utils.mjs";


export default class ProductDetails {
  constructor(productId, dataSource) {
    this.productId = productId;
    this.product = {};
    this.dataSource = dataSource;
  }


  async init() {
    // Fetches the specific product details using the ID
    // To load the full data (name, price, image) BEFORE attempting to render the HTML on the screen.
    this.product = await this.dataSource.findProductById(this.productId);

    // Renders the HTML on the page
    // Inject the content inside the <main> tag
    this.renderProductDetails("main");


    // Adds the event listener to the button
    // The "Add to Cart" button does not exist in the original HTML; it is dynamically generated by JS. Therefore, we can only attach the click event AFTER the previous step (render).
    // .bind(this) ensures that when clicked, the function knows that "this" refers to the ProductDetails class.
    document
      .getElementById("addToCart")
      .addEventListener("click", this.addToCart.bind(this));

    document
      .getElementById("addToWishlist")
      .addEventListener("click", this.addToWishlist.bind(this));
  }


  addToCart() {
    // This logic was previously in product.js
    // Encapsulation. It is good practice to keep everything related to product actions inside the class that manages it.
    let cartItems = getLocalStorage("so-cart") || [];

    // 1. Check if the item is already in the cart using its ID
    const existingItem = cartItems.find((item) => item.Id === this.product.Id);

    if (existingItem) {
      // 2. If it exists, increment its quantity
      existingItem.Quantity = (existingItem.Quantity || 1) + 1;
    } else {
      // 3. If it's a new item, assign Quantity = 1 and push it
      this.product.Quantity = 1;
      cartItems.push(this.product);
    }

    // 4. Save the updated array back to LocalStorage
    setLocalStorage("so-cart", cartItems);

    // 5. Update the visual badge with the total quantity of items
    const badge = document.getElementById("cart-count");
    if (badge) {
      // Calculate total physical items using reduce
      const totalQuantity = cartItems.reduce((total, item) => total + (item.Quantity || 1), 0);
      badge.textContent = totalQuantity;
      badge.style.display = "flex";
    }

    // 6. Micro-interaction: Change button feedback locally immediately upon click
    const addToCartBtn = document.getElementById("addToCart");
    if (addToCartBtn) {
      // Keep track of the original string ("Add to Cart")
      const originalText = addToCartBtn.innerText;

      // Transform button to success state
      addToCartBtn.innerText = "Added to Cart! 🛒";
      addToCartBtn.classList.add("btn-added");
      addToCartBtn.disabled = true; // Temporary disable lock to prevent quick duplicate clicks

      // Revert the button styles back to normal after 2 seconds
      setTimeout(() => {
        addToCartBtn.innerText = originalText;
        addToCartBtn.classList.remove("btn-added");
        addToCartBtn.disabled = false;
      }, 2000);
    }
  }

  addToWishlist() {
    // 1. Obtener la wishlist actual (usando tu utilidad)
    let wishlistItems = getLocalStorage("so-wishlist") || [];

    // 2. Verificar si el producto ya está en la wishlist
    const existingItem = wishlistItems.find((item) => item.Id === this.product.Id);

    const wishlistBtn = document.getElementById("addToWishlist");
    const originalText = wishlistBtn.innerText;

    if (!existingItem) {
      // 3. Si es nuevo, lo empujamos al array y guardamos
      wishlistItems.push(this.product);
      setLocalStorage("so-wishlist", wishlistItems);

      // Micro-interacción: Estado de éxito
      if (wishlistBtn) {
        wishlistBtn.innerText = "Added to Wishlist! ❤️";
        wishlistBtn.classList.add("btn-added"); // Reutilizamos tu clase CSS
        wishlistBtn.disabled = true;

        setTimeout(() => {
          wishlistBtn.innerText = originalText;
          wishlistBtn.classList.remove("btn-added");
          wishlistBtn.disabled = false;
        }, 2000);
      }
    } else {
      // 4. Si ya existe, le damos retroalimentación al usuario
      if (wishlistBtn) {
        wishlistBtn.innerText = "Already in Wishlist! 🤍";
        wishlistBtn.disabled = true;

        setTimeout(() => {
          wishlistBtn.innerText = originalText;
          wishlistBtn.disabled = false;
        }, 2000);
      }
    }
  }

  renderProductDetails(selector) {
    const element = document.querySelector(selector);

    const html = `
      <section class="product-detail">
        <h3>${this.product.Brand.Name}</h3>
        <h2 class="divider">${this.product.NameWithoutBrand}</h2>
        <img
          class="divider"
          src="${this.product.Images.PrimaryLarge}"
          alt="${this.product.NameWithoutBrand}"
        />
        <p class="product-card__price">$${this.product.FinalPrice}</p>
        <p class="product__color">${this.product.Colors[0].ColorName}</p>
        <p class="product__description">
          ${this.product.DescriptionHtmlSimple}
        </p>
        
        <!-- Aquí colocas el contenedor contenedor con sus nuevas clases -->
        <div class="product-detail__actions">
          <button id="addToCart" class="btn-primary" data-id="${this.product.Id}">Add to Cart</button>
          <button id="addToWishlist" class="btn-secondary" data-id="${this.product.Id}">❤️ Add to Wishlist</button>
        </div>
      </section>`;

    element.insertAdjacentHTML("afterBegin", html);
  }
}

